
["RF Furnace Fuel Temperature Settings"]
	#These values are 32-bit signed integer. (Maximum value is about 2.147G)
	#Temperature of RF Furnace Fuel 0
	rfFuel0Temp = 20
	#Temperature of RF Furnace Fuel 1
	rfFuel1Temp = 90
	#Temperature of RF Furnace Fuel 2
	rfFuel2Temp = 225
	#Temperature of RF Furnace Fuel 3
	rfFuel3Temp = 402
	#Temperature of RF Furnace Fuel 4
	rfFuel4Temp = 625
	#Temperature of RF Furnace Fuel 5
	rfFuel5Temp = 902
	#Temperature of RF Furnace Fuel 6
	rfFuel6Temp = 1230
	#Temperature of RF Furnace Fuel 7
	rfFuel7Temp = 1603
	#Temperature of RF Furnace Fuel 8
	rfFuel8Temp = 2026
	#Temperature of RF Furnace Fuel 9
	rfFuel9Temp = 2494
	#Temperature of RF Furnace Fuel 10
	rfFuel10Temp = 3036
	#Temperature of RF Furnace Fuel 11
	rfFuel11Temp = 3594
	#Temperature of RF Furnace Fuel 12
	rfFuel12Temp = 4240
	#Temperature of RF Furnace Fuel 13
	rfFuel13Temp = 5095
	#Temperature of RF Furnace Fuel 14
	rfFuel14Temp = 5647
	#Temperature of RF Furnace Fuel 15
	rfFuel15Temp = 6397
	#Temperature of RF Furnace Fuel 16
	rfFuel16Temp = 7242
	#Temperature of RF Furnace Fuel 17
	rfFuel17Temp = 8101
	#Temperature of RF Furnace Fuel 18
	rfFuel18Temp = 9039
	#Temperature of RF Furnace Fuel 19
	rfFuel19Temp = 10000

["RF Furnace Fuel Speed Rate Settings"]
	#These values are 32-bit signed integer. (Maximum value is about 2.147G)
	#The actual speed multiplier is calculated by dividing this value by 10.
	#For example, setting it to 100 results in 10x speed, and 25 results in 2.5x speed.
	#Speed Rate of RF Furnace Fuel 0
	rfRate0Temp = 5
	#Speed Rate of RF Furnace Fuel 1
	rfRate1Temp = 10
	#Speed Rate of RF Furnace Fuel 2
	rfRate2Temp = 15
	#Speed Rate of RF Furnace Fuel 3
	rfRate3Temp = 20
	#Speed Rate of RF Furnace Fuel 4
	rfRate4Temp = 25
	#Speed Rate of RF Furnace Fuel 5
	rfRate5Temp = 30
	#Speed Rate of RF Furnace Fuel 6
	rfRate6Temp = 35
	#Speed Rate of RF Furnace Fuel 7
	rfRate7Temp = 40
	#Speed Rate of RF Furnace Fuel 8
	rfRate8Temp = 45
	#Speed Rate of RF Furnace Fuel 9
	rfRate9Temp = 50
	#Speed Rate of RF Furnace Fuel 10
	rfRate10Temp = 55
	#Speed Rate of RF Furnace Fuel 11
	rfRate11Temp = 60
	#Speed Rate of RF Furnace Fuel 12
	rfRate12Temp = 65
	#Speed Rate of RF Furnace Fuel 13
	rfRate13Temp = 70
	#Speed Rate of RF Furnace Fuel 14
	rfRate14Temp = 75
	#Speed Rate of RF Furnace Fuel 15
	rfRate15Temp = 80
	#Speed Rate of RF Furnace Fuel 16
	rfRate16Temp = 85
	#Speed Rate of RF Furnace Fuel 17
	rfRate17Temp = 90
	#Speed Rate of RF Furnace Fuel 18
	rfRate18Temp = 95
	#Speed Rate of RF Furnace Fuel 19
	rfRate19Temp = 100

["Tool/Armor Slots Settings"]
	#These values are 32-bit signed integer. (Maximum value is about 2.147G)
	#Upgrade Slots of Blitz Gun
	blitzGunUpgradeSlots = 3
	#Ability Slots of Blitz Gun
	blitzGunAbilitySlots = 1
	#Upgrade Slots of MekaEdge
	mekaEdgeUpgradeSlots = 3
	#Ability Slots of MekaEdge
	mekaEdgeAbilitySlots = 1
	#Upgrade Slots of Mekaplate Boots
	mekaplateBootsUpgradeSlots = 2
	#Defense Slots of Mekaplate Boots
	mekaplateBootsAbilitySlots = 3
	#Upgrade Slots of Mekaplate Chestplate
	mekaplateChestplateUpgradeSlots = 2
	#Defense Slots of Mekaplate Chestplate
	mekaplateChestplateAbilitySlots = 3
	#Upgrade Slots of Mekaplate Helmet
	mekaplateHelmetUpgradeSlots = 2
	#Defense Slots of Mekaplate Helmet
	mekaplateHelmetAbilitySlots = 3
	#Upgrade Slots of Mekaplate Leggings
	mekaplateLeggingsUpgradeSlots = 2
	#Defense Slots of Mekaplate Leggings
	mekaplateLeggingsAbilitySlots = 3
	#Upgrade Slots of Reforged Slashblade
	reforgedSlashbladeUpgradeSlots = 3
	#Ability Slots of Reforged Slashblade
	reforgedSlashbladeAbilitySlots = 1
	#Upgrade Slots of Revival Spellbook
	revivalSpellbookUpgradeSlots = 3
	#Ability Slots of Revival Spellbook
	revivalSpellbookAbilitySlots = 1
	#Upgrade Slots of Singular Gem Boots
	singularGemBootsUpgradeSlots = 2
	#Defense Slots of Singular Gem Boots
	singularGemBootsAbilitySlots = 3
	#Upgrade Slots of Singular Gem Chestplate
	singularGemChestplateUpgradeSlots = 2
	#Defense Slots of Singular Gem Chestplate
	singularGemChestplateAbilitySlots = 3
	#Upgrade Slots of Singular Gem Helmet
	singularGemHelmetUpgradeSlots = 2
	#Defense Slots of Singular Gem Helmet
	singularGemHelmetAbilitySlots = 3
	#Upgrade Slots of Singular Gem Leggings
	singularGemLeggingsUpgradeSlots = 2
	#Defense Slots of Singular Gem Leggings
	singularGemLeggingsAbilitySlots = 3
	#Upgrade Slots of battlesign
	battlesignUpgradeSlots = 1
	#Ability Slots of battlesign
	battlesignAbilitySlots = 3
	#Upgrade Slots of Broad Axe
	broadAxeUpgradeSlots = 1
	#Defense Slots of Broad Axe
	broadAxeAbilitySlots = 2
	#Upgrade Slots of Cleaver
	cleaverUpgradeSlots = 1
	#Defense Slots of Cleaver
	cleaverAbilitySlots = 2
	#Upgrade Slots of Crossbow
	crossbowUpgradeSlots = 1
	#Defense Slots of Crossbow
	crossbowAbilitySlots = 3
	#Upgrade Slots of Dagger
	daggerUpgradeSlots = 1
	#Defense Slots of Dagger
	daggerAbilitySlots = 3
	#Upgrade Slots of Earth_staff
	earth_staffUpgradeSlots = 2
	#Ability Slots of Earth_staff
	earth_staffAbilitySlots = 3
	#Defense Slots of Earth_staff
	earth_staffDefenseSlots = 2
	#Upgrade Slots of Ender_staff
	ender_staffUpgradeSlots = 2
	#Ability Slots of Ender_staff
	ender_staffAbilitySlots = 1
	#Defense Slots of Ender_staff
	ender_staffDefenseSlots = 3
	#Upgrade Slots of Excavator
	excavatorUpgradeSlots = 1
	#Defense Slots of Excavator
	excavatorAbilitySlots = 2
	#Defense Slots of Flint And Brick
	flintAndBrickDefenseSlots = 1
	#Upgrade Slots of Hand Axe
	handAxeUpgradeSlots = 1
	#Defense Slots of Hand Axe
	handAxeAbilitySlots = 3
	#Upgrade Slots of Ichor Staff
	ichorStaffUpgradeSlots = 3
	#Defense Slots of Ichor Staff
	ichorStaffAbilitySlots = 2
	#Upgrade Slots of Kama
	kamaUpgradeSlots = 1
	#Defense Slots of Kama
	kamaAbilitySlots = 3
	#Upgrade Slots of Longbow
	longbowUpgradeSlots = 1
	#Defense Slots of Longbow
	longbowAbilitySlots = 2
	#Upgrade Slots of Mattock
	mattockUpgradeSlots = 1
	#Defense Slots of Mattock
	mattockAbilitySlots = 3
	#Upgrade Slots of Melting Pan
	meltingPanUpgradeSlots = 2
	#Ability Slots of Melting Pan
	meltingPanAbilitySlots = 1
	#Defense Slots of Melting Pan
	meltingPanDefenseSlots = 1
	#Upgrade Slots of Pickadze
	pickadzeUpgradeSlots = 1
	#Defense Slots of Pickadze
	pickadzeAbilitySlots = 3
	#Upgrade Slots of Pickaxe
	pickaxeUpgradeSlots = 1
	#Defense Slots of Pickaxe
	pickaxeAbilitySlots = 3
	#Ability Slots of Plate Boots
	plateBootsAbilitySlots = 3
	#Defense Slots of Plate Boots
	plateBootsDefenseSlots = 2
	#Ability Slots of Plate Chestplate
	plateChestplateAbilitySlots = 3
	#Defense Slots of Plate Chestplate
	plateChestplateDefenseSlots = 2
	#Ability Slots of Plate Helmet
	plateHelmetAbilitySlots = 3
	#Defense Slots of Plate Helmet
	plateHelmetDefenseSlots = 2
	#Ability Slots of Plate Leggings
	plateLeggingsAbilitySlots = 3
	#Defense Slots of Plate Leggings
	plateLeggingsDefenseSlots = 2
	#Ability Slots of Plate Shield
	plateShieldAbilitySlots = 3
	#Defense Slots of Plate Shield
	plateShieldDefenseSlots = 2
	#Upgrade Slots of Scythe
	scytheUpgradeSlots = 1
	#Defense Slots of Scythe
	scytheAbilitySlots = 2
	#Upgrade Slots of Sky Staff
	skyStaffUpgradeSlots = 2
	#Defense Slots of Sky Staff
	skyStaffAbilitySlots = 5
	#Upgrade Slots of Sledge Hammer
	sledgeHammerUpgradeSlots = 1
	#Defense Slots of Sledge Hammer
	sledgeHammerAbilitySlots = 2
	#Upgrade Slots of Slime Boots
	slimeBootsUpgradeSlots = 1
	#Defense Slots of Slime Boots
	slimeBootsAbilitySlots = 5
	#Upgrade Slots of Slime Chestplate
	slimeChestplateUpgradeSlots = 1
	#Defense Slots of Slime Chestplate
	slimeChestplateAbilitySlots = 5
	#Upgrade Slots of Slime Helmet
	slimeHelmetUpgradeSlots = 1
	#Defense Slots of Slime Helmet
	slimeHelmetAbilitySlots = 5
	#Upgrade Slots of Slime Leggings
	slimeLeggingsUpgradeSlots = 1
	#Defense Slots of Slime Leggings
	slimeLeggingsAbilitySlots = 5
	#Upgrade Slots of Swasher
	swasherUpgradeSlots = 1
	#Defense Slots of Swasher
	swasherAbilitySlots = 3
	#Upgrade Slots of Sword
	swordUpgradeSlots = 1
	#Defense Slots of Sword
	swordAbilitySlots = 3
	#Upgrade Slots of Travelers Boots
	travelersBootsUpgradeSlots = 1
	#Ability Slots of Travelers Boots
	travelersBootsAbilitySlots = 2
	#Defense Slots of Travelers Boots
	travelersBootsDefenseSlots = 2
	#Upgrade Slots of Travelers Chestplate
	travelersChestplateUpgradeSlots = 1
	#Ability Slots of Travelers Chestplate
	travelersChestplateAbilitySlots = 2
	#Defense Slots of Travelers Chestplate
	travelersChestplateDefenseSlots = 2
	#Upgrade Slots of Travelers Helmet
	travelersHelmetUpgradeSlots = 1
	#Ability Slots of Travelers Helmet
	travelersHelmetAbilitySlots = 2
	#Defense Slots of Travelers Helmet
	travelersHelmetDefenseSlots = 2
	#Upgrade Slots of Travelers Leggings
	travelersLeggingsUpgradeSlots = 1
	#Ability Slots of Travelers Leggings
	travelersLeggingsAbilitySlots = 2
	#Defense Slots of Travelers Leggings
	travelersLeggingsDefenseSlots = 2
	#Upgrade Slots of Travelers Shield
	travelersShieldUpgradeSlots = 1
	#Ability Slots of Travelers Shield
	travelersShieldAbilitySlots = 2
	#Defense Slots of Travelers Shield
	travelersShieldDefenseSlots = 2
	#Upgrade Slots of Vein Hammer
	veinHammerUpgradeSlots = 1
	#Defense Slots of Vein Hammer
	veinHammerAbilitySlots = 2
	#Upgrade Slots of War Pick
	warPickUpgradeSlots = 1
	#Defense Slots of War Pick
	warPickAbilitySlots = 3

["Modifier Level Settings"]
	#These values are 32-bit signed integer. (Maximum value is about 2.147G)
	#Max Level of Springy
	springyMaxLevel = 3
	#Max Level of Magic Protection
	magicProtectionMaxLevel = 32767
	#Max Level of Dragonborn
	dragonbornMaxLevel = 32767
	#Max Level of Overload
	overloadMaxLevel = 32767
	#Max Level of Hydraulic from Shard
	hydraulicfromShardMaxLevel = 5
	#Max Level of Offhanded
	offhandedMaxLevel = 2
	#Max Level of Padded
	paddedMaxLevel = 3
	#Max Level of Hydraulic from Block
	hydraulicfromBlockMaxLevel = 5
	#Max Level of Koshirae
	koshiraeMaxLevel = 32767
	#Max Level of Bane of Sssss
	baneofSssssMaxLevel = 5
	#Max Level of Spilling
	spillingMaxLevel = 32767
	#Max Level of Cardboard
	cardboardMaxLevel = 32767
	#Max Level of Thorns
	thornsMaxLevel = 3
	#Max Level of Lightspeed from Block
	lightspeedfromBlockMaxLevel = 5
	#Max Level of Swift Sneak
	swiftSneakMaxLevel = 5
	#Max Level of Trueshot
	trueshotMaxLevel = 3
	#Max Level of Speedy from Block
	speedyfromBlockMaxLevel = 3
	#Max Level of Sweeping Edge
	sweepingEdgeMaxLevel = 3
	#Max Level of Severing
	severingMaxLevel = 3
	#Max Level of Necrotic
	necroticMaxLevel = 5
	#Max Level of Trick Quiver
	trickQuiverMaxLevel = 2
	#Max Level of Swiftstrike from Shard
	swiftstrikefromShardMaxLevel = 5
	#Max Level of Haste from Dust
	hastefromDustMaxLevel = 5
	#Max Level of Slurping
	slurpingMaxLevel = 32767
	#Max Level of Revitalizing
	revitalizingMaxLevel = 32767
	#Max Level of Reach
	reachMaxLevel = 32767
	#Max Level of Power
	powerMaxLevel = 5
	#Max Level of Turtle Shell
	turtleShellMaxLevel = 32767
	#Max Level of Socket
	socketMaxLevel = 5
	#Max Level of Wetting
	wettingMaxLevel = 32767
	#Max Level of Blasting
	blastingMaxLevel = 5
	#Max Level of Blast Protection
	blastProtectionMaxLevel = 32767
	#Max Level of Boundless
	boundlessMaxLevel = 2
	#Max Level of Blindshot
	blindshotMaxLevel = 32767
	#Max Level of Multishot
	multishotMaxLevel = 32767
	#Max Level of Radiation Shielding
	radiationShieldingMaxLevel = 32767
	#Max Level of Double Jump
	doubleJumpMaxLevel = 32767
	#Max Level of Infernal
	infernalMaxLevel = 32767
	#Max Level of Override
	overrideMaxLevel = 32767
	#Max Level of Tank
	tankMaxLevel = 32767
	#Max Level of Sensor
	sensorMaxLevel = 32767
	#Max Level of Sharpness from Shard
	sharpnessfromShardMaxLevel = 5
	#Max Level of Speedy from Dust
	speedyfromDustMaxLevel = 3
	#Max Level of Experienced
	experiencedMaxLevel = 5
	#Max Level of Step up
	stepupMaxLevel = 2
	#Max Level of Farsighted
	farsightedMaxLevel = 32767
	#Max Level of Projectile Protection
	projectileProtectionMaxLevel = 32767
	#Max Level of Soulspeed
	soulspeedMaxLevel = 3
	#Max Level of Hurricane
	hurricaneMaxLevel = 32767
	#Max Level of Gilded
	gildedMaxLevel = 32767
	#Max Level of Impaling
	impalingMaxLevel = 4
	#Max Level of Antiaquatic
	antiaquaticMaxLevel = 5
	#Max Level of Melee Protection
	meleeProtectionMaxLevel = 32767
	#Max Level of Depth Strider
	depthStriderMaxLevel = 3
	#Max Level of Pockets
	pocketsMaxLevel = 32767
	#Max Level of Strength
	strengthMaxLevel = 32767
	#Max Level of Hidden Proud
	hiddenProudMaxLevel = 32767
	#Max Level of Expanded
	expandedMaxLevel = 32767
	#Max Level of Shulking
	shulkingMaxLevel = 32767
	#Max Level of Mekanic
	mekanicMaxLevel = 32767
	#Max Level of Hydraulic from Bricks
	hydraulicfromBricksMaxLevel = 5
	#Max Level of Fiery
	fieryMaxLevel = 5
	#Max Level of Spitting
	spittingMaxLevel = 32767
	#Max Level of Sharpness from Block
	sharpnessfromBlockMaxLevel = 5
	#Max Level of Haste from Block
	hastefromBlockMaxLevel = 5
	#Max Level of Punch
	punchMaxLevel = 5
	#Max Level of Bursting
	burstingMaxLevel = 32767
	#Max Level of Killager from Block
	killagerfromBlockMaxLevel = 5
	#Max Level of Pierce
	pierceMaxLevel = 3
	#Max Level of Bulk Quiver
	bulkQuiverMaxLevel = 32767
	#Max Level of Gravity
	gravityMaxLevel = 32767
	#Max Level of Reflecting
	reflectingMaxLevel = 32767
	#Max Level of Fire Protection
	fireProtectionMaxLevel = 32767
	#Max Level of Lightspeed from Dust
	lightspeedfromDustMaxLevel = 5
	#Max Level of Overforced
	overforcedMaxLevel = 5
	#Max Level of Shield Strap
	shieldStrapMaxLevel = 32767
	#Max Level of Embossment
	embossmentMaxLevel = 32767
	#Max Level of Knockback
	knockbackMaxLevel = 3
	#Max Level of Killager from Dust
	killagerfromDustMaxLevel = 5
	#Max Level of Feather Falling
	featherFallingMaxLevel = 4
	#Max Level of Respiration
	respirationMaxLevel = 3
	#Max Level of Item Frame
	itemFrameMaxLevel = 32767
	#Max Level of Freezing
	freezingMaxLevel = 3
	#Max Level of Abyssal
	abyssalMaxLevel = 32767
	#Max Level of Reinforced
	reinforcedMaxLevel = 5
	#Max Level of Magnetic
	magneticMaxLevel = 5
	#Max Level of Swiftstrike from Block
	swiftstrikefromBlockMaxLevel = 5
	#Max Level of Cooling
	coolingMaxLevel = 5
	#Max Level of Konpaku
	konpakuMaxLevel = 32767
	#Max Level of Quick Charge
	quickChargeMaxLevel = 4
	#Max Level of Ricochet
	ricochetMaxLevel = 2
	#Max Level of Splashing
	splashingMaxLevel = 32767
	#Max Level of Smelting
	smeltingMaxLevel = 32767
	#Max Level of Nearsighted
	nearsightedMaxLevel = 32767
	#Max Level of Smite
	smiteMaxLevel = 5
	#Max Level of Overcasting
	overcastingMaxLevel = 32767

["Catalyst Settings"]
	#If set to true, the catalyst will consume the Slashblade upon use.
	shouldConsumeSlashblade = true

