
#Machine Energy Storage Config. This config is synced from server to client.
[storage]
	#Base energy storage (Joules).
	recycler = "20000"
	#Base energy storage (Joules).
	plantingStation = "80000"
	#Base energy storage (Joules).
	cnc_stamper = "20000"
	#Base energy storage (Joules).
	cnc_lathe = "20000"
	#Base energy storage (Joules).
	cnc_rollingMill = "20000"
	#Base energy storage (Joules).
	ambientGasCollector = "40000"
	#Base energy storage (Joules).
	wirelessChargingStation = "10000000"

	#Settings for configuring Replicator Energy Storage
	[storage.replicator]
		#Base energy storage (Joules).
		itemReplicator = "102400000"
		#Base energy storage (Joules).
		fluidReplicator = "102400000"

